version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn loftmebel.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    ports:
      - 8001:8001
    expose:
      - 8001
    env_file:
      - ./.env.prod
    depends_on:
      - db
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    logging:
      options:
        max-size: 10m

volumes:
  postgres_data:
  static_volume:
  media_volume:
