# Generated by Django 3.2.9 on 2022-03-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220304_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=125)),
                ('code', models.CharField(max_length=6)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
